/* @name createExpenditures */
INSERT INTO expenditure (
    accnut_year,
    wdr_sfrnd_code,
    wdr_sfrnd_code_nm,
    sfrnd_code,
    sfrnd_nm_korean,
    accnut_se_code,
    accnut_se_nm,
    dept_code,
    detail_bsns_code,
    detail_bsns_nm,
    excut_de,
    budget_crntam,
    nxndr,
    cty,
    signgunon,
    etc_crntam,
    expndtram,
    orgnztnam,
    realm_code,
    realm_nm,
    sect_code,
    sect_nm,
    administ_sfrnd_code
  )
SELECT *
FROM unnest(
    ARRAY [$1::int[]],
    ARRAY [$2::text[]],
    ARRAY [$3::text[]],
    ARRAY [$4::text[]],
    ARRAY [$5::text[]],
    ARRAY [$6::text[]],
    ARRAY [$7::text[]],
    ARRAY [$8::text[]],
    ARRAY [$9::text[]],
    ARRAY [$10::text[]],
    ARRAY [$11::timestamptz[]],
    ARRAY [$12::bigint[]],
    ARRAY [$13::bigint[]],
    ARRAY [$14::bigint[]],
    ARRAY [$15::bigint[]],
    ARRAY [$16::bigint[]],
    ARRAY [$17::bigint[]],
    ARRAY [$18::bigint[]],
    ARRAY [$19::text[]],
    ARRAY [$20::text[]],
    ARRAY [$21::text[]],
    ARRAY [$22::text[]],
    ARRAY [$23::text[]]
  );