/* @name getCenterExpenditureByOffice */
SELECT SACTV_NM,
  sum(Y_YY_MEDI_KCUR_AMT) AS Y_YY_MEDI_KCUR_AMT_SUM,
  sum(Y_YY_DFN_MEDI_KCUR_AMT) AS Y_YY_DFN_MEDI_KCUR_AMT_SUM
FROM center_expenditure
WHERE CASE
    WHEN $2::int IS NULL THEN FSCL_YY = $1
    ELSE FSCL_YY >= $1
    AND FSCL_YY <= $2
  END
  AND OFFC_NM = $3
GROUP BY SACTV_NM
ORDER BY Y_YY_DFN_MEDI_KCUR_AMT_SUM DESC
LIMIT $4;