/* @name getCenterExpenditures */
SELECT OFFC_NM,
  sum(Y_YY_DFN_MEDI_KCUR_AMT) AS Y_YY_DFN_MEDI_KCUR_AMT_SUM
FROM center_expenditure
WHERE CASE
    WHEN $2::int IS NULL THEN FSCL_YY = $1
    ELSE FSCL_YY >= $1
    AND FSCL_YY <= $2
  END
GROUP BY OFFC_NM
ORDER BY Y_YY_DFN_MEDI_KCUR_AMT_SUM DESC;