/* @name getCefinByOffice */
SELECT OFFC_NM,
  SUM(Y_PREY_FIRST_KCUR_AMT) AS Y_PREY_FIRST_KCUR_AMT,
  SUM(Y_PREY_FNL_FRC_AMT) AS Y_PREY_FNL_FRC_AMT,
  SUM(Y_YY_MEDI_KCUR_AMT) AS Y_YY_MEDI_KCUR_AMT,
  SUM(Y_YY_DFN_MEDI_KCUR_AMT) AS Y_YY_DFN_MEDI_KCUR_AMT
FROM center_expenditure
WHERE CASE
    WHEN $1 THEN FLD_NM = ANY ($2)
    ELSE SECT_NM = ANY ($2)
  END
GROUP BY OFFC_NM
ORDER BY Y_YY_DFN_MEDI_KCUR_AMT DESC;