/* @name getCefinByOffice */
SELECT OFFC_NM,
  SUM(Y_YY_MEDI_KCUR_AMT) AS Y_YY_MEDI_KCUR_AMT,
  SUM(Y_YY_DFN_MEDI_KCUR_AMT) AS Y_YY_DFN_MEDI_KCUR_AMT
FROM center_expenditure
WHERE FSCL_YY BETWEEN $1 AND $2
  AND CASE
    WHEN $3 THEN FLD_NM = ANY ($4)
    ELSE SECT_NM = ANY ($4)
  END
GROUP BY OFFC_NM
ORDER BY Y_YY_DFN_MEDI_KCUR_AMT DESC;